version: "3.4"
services:
  evolution_frontend:
    container_name: evolution_frontend
    image: node:lts
    working_dir: /var/www/html/app/
    entrypoint: /bin/bash
    ports:
      - "8000:8000"
    volumes:
      - ./:/var/www/html/app
    tty: true